### ISSUE TITLE
Logstash pipeline bloqued

### ISSUE THREAD

**Issue by khalifanizar** [logstash-plugins/logstash-input-beats#118]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version:
`filebeat version 1.2.3 (amd64)`
`logstash 2.3.4`

- Filebeat config File:
```
filebeat:
   prospectors:
      -
           paths:
               - /home/collecte.log
           input_type: log
           document_type: log
           scan_frequency: 1s
           max_bytes: 10485760
           tail_files: true
   registry_file: /var/lib/filebeat/registry

output:
   logstash:
      hosts: ["**********"]
      worker: 1

shipper:

logging:
   files:
   rotateeverybytes: 10485760 # = 10MB
```

- Logstash config File:

```
input {
  beats {
        port => 5044
        #codec => "json"
  }
}

filter {
#data transformation using grok,kv,urldecode,mutate,prune
}

output {
stdout {
    codec => rubydebug
  }
               mongodb {
                        collection => "*******"
                        database   => "***********"
                        uri        => "*********"
                }
}

```

- Messages:
```
{:timestamp=>"2016-08-23T21:12:27.080000+0200", :message=>"CircuitBreaker::rescuing exceptions", :name=>"Beats input", :exception=>LogStash::Inputs::Beats::InsertingToQueueTakeTooLong, :level=>:warn}
{:timestamp=>"2016-08-23T21:12:27.080000+0200", :message=>"Beats input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecting new connection until the pipeline recover.", :exception=>LogStash::Inputs::BeatsSupport::CircuitBreaker::HalfOpenBreaker, :level=>:warn}
{:timestamp=>"2016-08-23T21:12:28.085000+0200", :message=>"Beats input: the pipeline is blocked, temporary refusing new connection.", :reconnect_backoff_sleep=>0.5, :level=>:warn}
{:timestamp=>"2016-08-23T21:12:28.085000+0200", :message=>"CircuitBreaker::Open", :name=>"Beats input", :level=>:warn}
{:timestamp=>"2016-08-23T21:12:28.086000+0200", :message=>"Beats input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecting new connection until the pipeline recover.", :exception=>LogStash::Inputs::BeatsSupport::CircuitBreaker::OpenBreaker, :level=>:warn}
{:timestamp=>"2016-08-23T21:12:28.585000+0200", :message=>"Beats input: the pipeline is blocked, temporary refusing new connection.", :reconnect_backoff_sleep=>0.5, :level=>:warn}
{:timestamp=>"2016-08-23T21:12:29.086000+0200", :message=>"Beats input: the pipeline is blocked, temporary refusing new connection.", :reconnect_backoff_sleep=>0.5, :level=>:warn}
```

- I dont know what really block the pipeline?
- Is it because the flux of input is more much greater than the output ?
- How can i get a graph to show the average of Logstash requests?

Thanks for help
B.R
