### ISSUE TITLE
Setting verify_mode to NONE results in FORCE_PEER in SslSimpleBuilder.java

### ISSUE THREAD

**Issue by nick-george** [logstash-plugins/logstash-input-beats#196]
Hi,

If the user has set verify_mode to NONE in the logstash beats input configuration, it is overridden by the default value set by the code in SslSimpleBuilder.java (https://github.com/logstash-plugins/logstash-input-beats/blob/master/src/main/java/org/logstash/netty/SslSimpleBuilder.java), see below:

    SslClientVerifyMode verifyMode = SslClientVerifyMode.FORCE_PEER;
This is because the Java code has no concept of NONE as the ClientVerifyMode.

Due to various other limitations in Logstash, I am having to pass in a non-empty array of certificate authorities. Because of this, requireClientAuth() will always return true; which in turn, actually sets the verify mode to FORCE_PEER - even though I set it to NONE in the filter configuration. As a result of this, all SSL connections fail. 

Could you please fix this behaviour? I am happy to write a pull-request, but have been unable to run your tests successfully in the past. 

Nick

**Comment by Sakorah** [comment]
Hi,

I'm running into the same issue here.
LS: 5.6.3
Filebeat 5.6.3

I set the beats input to:
``` 
beats {  
  port => "8214"  
  host => "10.37.129.203"  
  tags => "filebeat"  
  ssl => true  
  ssl_certificate => "/etc/logstash/certs/minion-elk01.shared-01-cert.pem"  
  ssl_key => "/etc/logstash/certs/minion-elk01.shared-02-key.pkcs8"  
  ssl_certificate_authorities => "/etc/logstash/certs/minion-elk01.shared-03-ca.pem" 
  ssl_verify_mode => "none"  
  tls_min_version => 1.2  
 }
```
And the Beat config to:
```
output:
  logstash:
    hosts: ["elk-vip01.shared:8214", "elk-vip02.shared:8214"]
    loadbalance: true
    ssl.certificate_authorities: ["/etc/logstash/certs/minion-elk01.shared-03-ca.pem"]
    ssl.supported_protocols: [TLSv1.2]
    ssl.verification_mode: full
```

If I give filebeat a client certificate it works, without a certificate the handshake fails although LS should not even ask the client for a certificate.
