### ISSUE TITLE
Unable to get SSL working. Weird error

### ISSUE THREAD

**Issue by pklanka** [logstash-plugins/logstash-input-beats#304]
Original discussion here - https://discuss.elastic.co/t/please-help-error-in-logstash-shipper/120058. We are receiving an unusual error in our logstash plain log - 

[2018-02-15T19:05:54,771][ERROR][org.logstash.beats.BeatsHandler] Exception: javax.net.ssl.SSLHandshakeException: error:10000412:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE

The above message repeating for every log entry we receive which is apparently a bug since our protocol is not using SSLV3. Could someone please help.

- Version: Logstash 5.6.7
- Operating System: CentOS on AWS
- Config File (if you have sensitive info, please remove it):
Below is our shipper input configuration -

```
input {
  beats {
    port => 5044
    ssl => true
    ssl_certificate => "${LS_SETTINGS_DIR:logstash-shipper-configuration}/certs/logstash-shipper.crt"
    ssl_key => "${LS_SETTINGS_DIR:logstash-shipper-configuration}/certs/logstash-shipper.key"
  }
}
```

Below is our shipper output configuration -

```
output {
  redis {
    port => 6379
    host => REDACTED
    password => REDACTED
    timeout => 10
    data_type => "list"
    batch => "true"
  }
}
```

Here is our filebeat configuration - 
```
output:
  logstash:
    hosts: ["REDACTED:5044"]
    worker: 3
    compression_level: 3

    # Optional TLS. By default is off.
    ssl:
      certificate_authorities: ["/path/to/cafile.crt"]
      insecure: true
      cipher_suites: []
      curve_types: []
```
