### ISSUE TITLE
Beats Input: Remote connection closed unsupported protocol 42 warning

### ISSUE THREAD

**Issue by MarkGoldsmith1987** [logstash-plugins/logstash-input-beats#44]
I'm seeing this filling up my logstash log:

{:timestamp=>"2016-01-15T11:46:37.690000+0000", :message=>"Beats Input: Remote connection closed", :peer=>"xx.xx.xx.xx:41919", :exception=>#<Lumberjack::Beats::Connection::ConnectionClosed: Lumberjack::Beats::Connection::ConnectionClosed wrapping: Lumberjack::Beats::Parser::UnsupportedProtocol, unsupported protocol 42>, :level=>:warn}

Prior to upgrading to the latest version of the logstash-input-beats plugin with was being reported as an error, however since upgrading the logs from filebeat are being processed by its completely spamming the logstash.log file with these warnings.

Versions
Filebeats 1.0.1
Logstash-input-beats  2.1.2
Logstash: 2.1.1

**Comment by alexkappa** [comment]
Same issue here.

```
{:timestamp=>"2016-01-20T11:36:04.761000+0000", :message=>"Beats Input: Remote connection closed", :peer=>"10.244.5.0:39878", :exception=>#<Lumberjack::Beats::Connection::ConnectionClosed: Lumberjack::Beats::Connection::ConnectionClosed wrapping: Lumberjack::Beats::Parser::UnsupportedProtocol, unsupported protocol 72>, :level=>:warn}
```
```
$ filebeat --version
filebeat version 1.0.1 (amd64)
```
```
$ logstash --version
logstash 2.1.1
```

**Comment by ph** [comment]
In the 2.1.0 release of the plugin I have added more granular loggings, but this certainly concerning if you  see this really often in your logs, Is there any correlating log on the filebeat side? 

This error is originating at the protocol level inside the parser state machine, anything else is trying to connect to the 5044 port?

**Comment by ph** [comment]
If you try to connect to the input with telnet and try to send something you will get a protocol error.

```
Settings: Default filter workers: 2
Logstash startup completed
Beats Input: Remote connection closed {:peer=>"0:0:0:0:0:0:0:1:57640", :exception=>#<Lumberjack::Beats::Connection::ConnectionClosed: Lumberjack::Beats::Connection::ConnectionClosed wrapping: Lumberjack::Beats::Parser::UnsupportedProtocol, unsupported protocol 100>, :level=>:warn}
````

@alexkappa  Not sure if its related, the peer address is ending with 0?

**Comment by McStork** [comment]
I also get often this error with Logstash 2.2 / Beats 1.1.
Error only appears when Beats are running so I doubt it is caused by another protocol trying to connect to 5044.
```
{:timestamp=>"2016-01-26T10:56:11.614000+0100", :message=>"Beats Input: Remote connection closed", :peer=>"127.0.0.1:51407", :exception=>#<Lumberjack::Beats::Connection::ConnectionClosed: Lumberjack::Beats::Connection::ConnectionClosed wrapping: Lumberjack::Beats::Parser::UnsupportedProtocol, unsupported protocol 0>, :level=>:warn}
```
It often is ```unsupported protocol 0```or  ```unsupported protocol 8``` and most of the time occurs at the beginning of output from Packetbeat to Logstash.

**Comment by ph** [comment]
I was able to get that error from time to time with the latest filebeat 1.1, I will look into it as soon as possible.

**Comment by alexkappa** [comment]
@ph is it bad if it ends with a 0? I'm sending logstash events from filebeats from several hosts. One of those hosts IP ends with a 0 but others not necessarily (aws autoscaling). I can provide a more detailed log if that helps.

**Comment by asemt** [comment]
Same error here with following versions (all Linux amd64):
- Logstash: logstash 2.1.1
- Logstash logstash-input-beats plugin: 2.1.2
- Packetbeat: 1.1.0 and 1.0.1

Would be really cool to have a more verbose error message.

**Comment by cero-t** [comment]
Same error with following versions (Amazon Linux)

Logstash 2.2.2 (new instance, clean environment)
Filebeat 1.1.1 (old instance, dirty environment!!)

But when I created a new Amazon Linux instance and installed Filebeat,
I could not reproduce this error.

I guess some other modules or libraries might cause this problem.
I will notice it when I find it.

**Comment by bwhaley** [comment]
FWIW I was seeing this (Amazon Linux, Logstash 2.2.0, Filebeat 1.1.0) until I updated the logstash-input-beats plugin from 2.1.2 to 2.1.4. No more messages.

**Comment by matglas** [comment]
I only have this error when I'm trying to connect through TLS. When I don't connect through TLS everything works fine. I have a docker setup with 3 hosts. And the problem is exactly the same everytime I try the settings with TLS it gives me 

```
Lumberjack::Beats::Parser::UnsupportedProtocol, unsupported protocol 115
```

And in Filebeat:
```
host1_1 | 2016/03/07 19:29:59.628451 single.go:76: INFO Error publishing events (retrying): EOF
host1_1 | 2016/03/07 19:29:59.628482 single.go:152: INFO send fail
host1_1 | 2016/03/07 19:29:59.628494 single.go:159: INFO backoff retry: 1s
```

I have a selfsigned certificate which works when testing it through openssl
`openssl s_client -connect logstash:5044`

It gives me.
```
CONNECTED(00000003)
depth=0 CN = logstash
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = logstash
verify return:1
---
Certificate chain
 0 s:/CN=logstash
   i:/CN=logstash
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIC+TCCAeGgAwIBAgIJAO1XepeRdCZNMA0GCSqGSIb3DQEBCwUAMBMxETAPBgNV
BAMMCGxvZ3N0YXNoMB4XDTE2MDMwNDE0NTEzMVoXDTI2MDMwMjE0NTEzMVowEzER
MA8GA1UEAwwIbG9nc3Rhc2gwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQDIojXUlJ0PyFepfiQr8Waz21nao7Hoq7SWMvWUYt54YtusYkn+JFK/HcqsaFEO
Dq2Xpahvq7vddwCesPbuVeW2b8WoPZescOKoFbAdUX+ZqnTvGXnUvjDI0GlWkCsa
pad3fwB7oeUgQTRrokNxtue9ix0A0gkDiE1LT+bbXI3K52/YWjy7wiPqzR9fsHoU
JSiuwRRzyYZ6sS2QEDssbSqQPsPO4G13dMz7DDc/7uu1Vz3h1jVaCWWfQLA6OwtU
yixCjNN0UjKHQ13jzJjfsO76Vmy943VLasPF+ls0m6SvYPYbVUGP4AqcJqRNwArN
Q74tv2WGoyGPL2nDQsIRpHG7AgMBAAGjUDBOMB0GA1UdDgQWBBQ4bFWWLEzRysop
cBNid0k6faP6kzAfBgNVHSMEGDAWgBQ4bFWWLEzRysopcBNid0k6faP6kzAMBgNV
HRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQB5W4ZfwMcuAGpKsH+D+vv/PC+X
o00o6k39NLdhOi5AOZbDcKmEin0O4FMrWUPaQI4zbYRwgk7u+9pwJeyGyh3yy+gX
Is7j2GoWd7tlFPAnE8l9jPt+gClWiSPhfzuSM7j6LV+LwkPiR7R1jdjYw+Bv8UE5
mrnwqHrdmFv4ZL1BuZ53uV3sMXoWDX6yBLjWt7xxldBnNVTyWAXqxytt+feCaRKh
nX1HSeamjptX34/WZ+y5rHpSHIONUY9yezqOmX4HJWtFHo5MJwxB5mb5GatqgNUe
y+MYSzNG83pNwtGiCFWzNrkms5u0O7Y/H2mMKi3eAReSByHvZ1sJFzNl1fXM
-----END CERTIFICATE-----
subject=/CN=logstash
issuer=/CN=logstash
---
No client certificate CA names sent
---
SSL handshake has read 1353 bytes and written 525 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-SHA
    Session-ID: 56DDD43597162ED3F158E701335EF0EA9C30121BA3B0751F2B94D2AD992EAE46
    Session-ID-ctx: 
    Master-Key: 1B9CFDD3EE0A7348B418AC01736B7EA598708C1B12B6B9DF9D8DEFDC39A9210B468248BA62B14635F8BAEBE8243FCDFE
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1457378357
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
---
```

But when connecting with the Filebeat or Topbeat it does not work.

I use version these versions 
Logstash 2.2.2
Filebeat 1.1.2
Topbeat 1.1.2

**Comment by matglas** [comment]
Filebeat.yml

```
filebeat:
  # List of prospectors to fetch data.
  prospectors:
    # Each - is a prospector. Below are the prospector specific configurations
    -
      # Paths that should be crawled and fetched. Glob based paths.
      # For each file found under this path, a harvester is started.
      paths:
        - "/var/log/apache2/*access.log"
        #- c:\programdata\elasticsearch\logs\*

      # Type of the files. Based on this the way the file is read is decided.
      # The different types cannot be mixed in one prospector
      #
      # Possible options are:
      # * log: Reads every line of the log file (default)
      # * stdin: Reads the standard in
      input_type: log

output:
  logstash:
    hosts: ["logstash:5044"]

  tls:
    # Certificate for TLS client authentication
    certificate: "/etc/pki/tls/certs/beats.crt"

    # Client Certificate Key
    certificate_key: "/etc/pki/tls/private/beats.key"

    insecure: true

  console:
    pretty: true
```

Topbeat.yml
```
input:
  period: 30
  procs: [".*"]

  # Statistics to collect (all enabled by default)
  stats:
    # per system statistics, by default is true
    system: true

    # per process statistics, by default is true
    process: false

    # file system information, by default is true
    filesystem: false

    # cpu usage per core, by default is false
    cpu_per_core: false

output:
  logstash:
    hosts: ["logstash:5044"]

  tls:
      # Certificate for TLS client authentication
      certificate: "/etc/pki/tls/certs/beats.crt"

      # Client Certificate Key
      certificate_key: "/etc/pki/tls/private/beats.key"

      insecure: true

  console:
    pretty: true
```

Input config in logstash.
```
input {
  beats {
    port => 5044
    ssl => true
    ssl_certificate => "/etc/pki/tls/certs/beats.crt"
    ssl_key => "/etc/pki/tls/private/beats.key"
  }
}
```

**Comment by ph** [comment]
@matglas I think this is the case of #47, Also since you are using a self signed certificate and the `logstash-input-beats` doesn't do any client side verification for now (until my PR is complete), It only does server verification. You can update your configuration to use `certificate_authorities` instead of the `certificate` and `certificate_key`, so you wont need to copy your private key to all the filebeat instances and only the certificate.

**Comment by jerrac** [comment]
I'm getting something like this when trying to receive topbeat logs from a Windows server.

logstash.log:

    {:timestamp=>"2016-03-16T15:52:32.087000-0700", :message=>"Beats Input: Remote connection closed", :peer=>"nn.nn.nn.nn:58826", :exception=>#<Lumberjack::Beats::Connection::ConnectionClosed: Lumberjack::Beats::Connection::ConnectionClosed wrapping: Lumberjack::Beats::Parser::UnsupportedProtocol, unsupported protocol 72>, :level=>:warn}

Logstash 2.2.2. Topbeat 1.1.2 is sending data to the beats input plugin on port 5043, as are a few other beats on other servers.

I'll post topbeat.yml when I get it.

Is there any info about the Windows server that would help?

**Comment by jerrac** [comment]
So, after looking at the topbeat.yml file my coworker sent me, I found that he was trying to send elasticsearch data to my logstash indexer... He hadn't uncommented the ```#logstash:``` line. Which gave him something like this:
```yaml
output:
  elasticsearch:
    hosts: ["localhost:9200"]
    hosts: ["indexer:5043"]
```

That would explain the protocol error, right?

He hasn't fixed it yet, so I can't confirm on my own.
