### ISSUE TITLE
Errors in logstash since upgrade to 2.2

### ISSUE THREAD

**Issue by chad-upton** [logstash-plugins/logstash-input-beats#46]
After upgrading logstash to the newest version that came out today, I'm seeing these messages in the logs constantly using the beats input plugin.

```
{:timestamp=>"2016-02-06T06:21:15.454000+0000", :message=>"Beats Input: Remote connection closed", :peer=>"10.0.5.242:11572", :exception=>#<Lumberjack::Beats::Connection::ConnectionClosed: Lumberjack::Beats::Connection::ConnectionClosed wrapping: EOFError, End of file reached>, :level=>:warn}
{:timestamp=>"2016-02-06T06:21:19.290000+0000", :message=>"Beats Input: Remote connection closed", :peer=>"10.0.1.169:28246", :exception=>#<Lumberjack::Beats::Connection::ConnectionClosed: Lumberjack::Beats::Connection::ConnectionClosed wrapping: EOFError, End of file reached>, :level=>:warn}
```

**Comment by plumpNation** [comment]
I am also seeing the same issue.

However, it was working earlier. I am removing the registry and elasicsearch indices and pushing all the logs in again. Worked several times without issue, then stopped.

Have reverted all changes to the working setup, still the issue persists.

**Comment by ph** [comment]
@chad-upton In the latest release of the plugin I have added more logging, in the previous version we have similar errors but were not reporting them.

I you look at your filebeat logs do you see any errors related in that time frame?

@plumpNation In your case it is normal you are closing the remote connection which trigger the EOF on the logstash.

**Comment by ph** [comment]
@plumpNation Thanks we are trying our best to help out :) You should look at our discuss forum.  https://discuss.elastic.co

**Comment by chad-upton** [comment]
@ph It's a constant stream of that error as soon as logstash is started.

My logstash collectors are behind an AWS ELB, nothing showing up in the filebeat logs.

Appreciate the help!

**Comment by ph** [comment]
@chad-upton Can you share both your logstash and filebeat configuration?

**Comment by chad-upton** [comment]
Filebeat.yml
```
############################# Filebeat ######################################
filebeat:
  prospectors:
    -
      # Linux system logs
      paths:
        - /var/log/messages
        - /var/log/secure
        - /var/log/cloud-init-output.log
        - /var/log/yum.log
      encoding: utf-8
      input_type: system
      fields:
        json: false
      fields_under_root: true
    -
      # Puma Logs
      paths:
        - /var/log/puma/puma.log
      encoding: utf-8
      input_type: puma
      fields:
        json: false
      fields_under_root: true
    -
      # Rails worker
      paths:
        - /var/log/worker/*.log
        - /var/log/worker/*.err
      encoding: utf-8
      input_type: railsworker
      fields:
        json: false
      fields_under_root: true
    -
      # Nginx logs
      paths:
        - /var/log/nginx/*.log
      encoding: utf-8
      input_type: nginx
      fields:
        json: false
      fields_under_root: true
    -
      # Ossec
      paths:
        - /var/ossec/logs/alerts/alerts.log
      encoding: utf-8
      input_type: ossec
      fields:
        json: false
      fields_under_root: true
    -
      # Elasticbeanstalk
      paths:
        - /var/log/eb-activity.log
        - /var/log/eb-version-deployment.log
      encoding: utf-8
      input_type: elasticbeanstalk
      fields:
        json: false
      fields_under_root: true

  registry_file: /var/lib/filebeat/registry
output:
  logstash:
    hosts: ["logs.example.com:5044"]
    worker: 1

shipper:
logging:
  files:
    rotateeverybytes: 10485760 # = 10MB
```

I have multiple filters but only a single input from filebeat.

logstash.conf.d/
```
# All client side logs come in via this method

input {
  beats {
    port => 5044
  }
}
```
