### ISSUE TITLE
logstash for windows error on filebeat shutdown

### ISSUE THREAD

**Issue by dmitriyett** [logstash-plugins/logstash-input-beats#9]
I'm using filebeat and logstash for logging and I've noticed strange error in logstash output:

```
�[31mBeats input: unhandled exception {:exception=>#<SystemCallError: Unknown error - ????????? ???? ????????????? ???????? ???????????? ???????????>, :backtrace=>["org/jruby/RubyIO.java:3020:in `sysread'", "D:/Repositories/logstashtests/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:330:in `read_socket'", "D:/Repositories/logstashtests/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:315:in `run'", "D:/Repositories/logstashtests/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/logstash/inputs/beats.rb:150:in `invoke'", "org/jruby/RubyProc.java:271:in `call'", "D:/Repositories/logstashtests/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/concurrent-ruby-0.9.1-java/lib/concurrent/executor/executor_service.rb:515:in `run'", "Concurrent$$JavaExecutorService$$Job_102551874.gen:13:in `run'"], :level=>:error}�[0m
```

My logstash.conf file:

```
input {
    beats {
        port => 5044
    }
}

output {
    stdout {}
}
```

My filebeat.yml file:

```
filebeat:
  prospectors:
    -
      paths:
        - "D:\\Repositories\\logstashtests\\logs.txt"
      type: log
output:
  logstash:
    enabled: true

    hosts: ["127.0.0.1:5044"]
```

It seems that everything works fine even with this exception, You can find some details in filebeat repo: elastic/filebeat#145
